from django.urls import path
from .views import (
    login_page,
    superadmin_home,
    upload_students,
    upload_attendance,
    delete_week,
    delete_results,
    mentor_dashboard,
    save_call,
    mark_message,
    mentor_report,
    coordinator_dashboard,
    coordinator_result_report,
    print_student,
    mentor_prefilled_sif_pdf,
    mentor_prefilled_sif_zip,
    lock_week,
    control_panel,
    update_mobile,
    view_attendance,
    semester_register,
    upload_results,
    upload_results_cancel,
    upload_results_progress,
    view_results,
    view_practical_marks,
    subjects_page,
    sif_marks_template,
    add_subject,
    edit_subject,
    delete_subject,
    mentor_result_calls,
    mentor_other_calls,
    mentor_print_sif,
    mentor_whatsapp_panel,
    download_whatsapp_extension,
    mentor_sif_marks,
    mentor_sif_marks_pdf,
    mentor_sif_marks_pdf_all,
    switch_module,
    manage_modules,
    rbac_create_coordinator,
    rbac_update_coordinator_modules,
    superadmin_change_password,
    save_result_call,
    save_other_call,
    mark_result_message,
    mentor_result_report,
)
from .mobile_api import (
    api_mobile_login,
    api_mobile_logout,
    api_mobile_weeks,
    api_mobile_modules,
    api_mobile_calls,
    api_mobile_save_call,
    api_mobile_mark_message,
    api_mobile_retry_list,
    api_mobile_result_cycles,
    api_mobile_result_calls,
    api_mobile_save_result_call,
    api_mobile_mark_result_message,
    api_mobile_result_retry_list,
    api_mobile_result_report,
    api_mobile_other_calls,
    api_mobile_save_other_call,
)

urlpatterns = [
    path('', login_page),
    path('home/', superadmin_home),
    path('mentor-dashboard/', mentor_dashboard),
    path('upload-students/', upload_students),
    path('upload-attendance/', upload_attendance),
    path('delete-week/', delete_week),
    path('delete-results/', delete_results),
    path('save-call/', save_call),
    path('mark-message/', mark_message),
    path('mentor-report/', mentor_report),
    path('print-student/<str:enrollment>/', print_student),
    path('mentor-prefilled-sif/<str:enrollment>/', mentor_prefilled_sif_pdf),
    path('mentor-prefilled-sif-all/', mentor_prefilled_sif_zip),
    path('reports/', coordinator_dashboard),
    path('lock-week/', lock_week),
    path('control-panel/', control_panel),
    path('update-mobile/', update_mobile),
    path('view-attendance/', view_attendance),
    path("semester-register/", semester_register, name="semester_register"),
    path("upload-results/", upload_results),
    path("upload-results/progress/<str:job_id>/", upload_results_progress),
    path("upload-results/cancel/<str:job_id>/", upload_results_cancel),
    path("view-results/", view_results),
    path("view-practical-marks/", view_practical_marks),
    path("subjects/", subjects_page),
    path("subjects/add/", add_subject),
    path("subjects/<int:subject_id>/edit/", edit_subject),
    path("subjects/<int:subject_id>/delete/", delete_subject),
    path("mentor-result-calls/", mentor_result_calls),
    path("mentor-other-calls/", mentor_other_calls),
    path("mentor-print-sif/", mentor_print_sif),
    path("mentor-whatsapp/", mentor_whatsapp_panel),
    path("mentor-whatsapp/extension-download/", download_whatsapp_extension),
    path("mentor-sif-marks/", mentor_sif_marks),
    path("mentor-sif-marks-pdf/<str:enrollment>/", mentor_sif_marks_pdf),
    path("mentor-sif-marks-pdf-all/", mentor_sif_marks_pdf_all),
    path("sif-marks-template/", sif_marks_template),
    path("switch-module/", switch_module),
    path("modules/", manage_modules),
    path("rbac/create-coordinator/", rbac_create_coordinator),
    path("rbac/update-coordinator-modules/", rbac_update_coordinator_modules),
    path("rbac/superadmin-change-password/", superadmin_change_password),
    path("save-result-call/", save_result_call),
    path("save-other-call/", save_other_call),
    path("mark-result-message/", mark_result_message),
    path("mentor-result-report/", mentor_result_report),
    path("result-reports/", coordinator_result_report),
    path("api/mobile/login/", api_mobile_login),
    path("api/mobile/logout/", api_mobile_logout),
    path("api/mobile/weeks/", api_mobile_weeks),
    path("api/mobile/modules/", api_mobile_modules),
    path("api/mobile/calls/", api_mobile_calls),
    path("api/mobile/save-call/", api_mobile_save_call),
    path("api/mobile/mark-message/", api_mobile_mark_message),
    path("api/mobile/retry-list/", api_mobile_retry_list),
    path("api/mobile/result-cycles/", api_mobile_result_cycles),
    path("api/mobile/result-calls/", api_mobile_result_calls),
    path("api/mobile/save-result-call/", api_mobile_save_result_call),
    path("api/mobile/mark-result-message/", api_mobile_mark_result_message),
    path("api/mobile/result-retry-list/", api_mobile_result_retry_list),
    path("api/mobile/result-report/", api_mobile_result_report),
    path("api/mobile/other-calls/", api_mobile_other_calls),
    path("api/mobile/save-other-call/", api_mobile_save_other_call),


]
